# Generated by Django 4.1.6 on 2023-02-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_appuser_first_name_alter_appuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='phone_number',
        ),
    ]
